# Use docker-based build environment (instead of openvz)
sudo: false

os:
  - linux
  - osx

language: java

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
    - '$HOME/.m2/repository'
