# seems to be required for jdk9
sudo: required

# required for oraclejdk9
dist: trusty
# required for oraclejdk9
group: edge

# disable -XX:MaxPermSize=192m
env:
- MAVEN_OPTS=-Xmx128m

language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9

matrix:
allow_failures:
- jdk: oraclejdk9

cache:
directories:
- '$HOME/.m2/repository'
install: /bin/true
